# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='articles/')),
                ('proj_title', models.CharField(max_length=25)),
                ('proj_link', models.CharField(max_length=50)),
                ('proj_description', models.CharField(max_length=2500)),
                ('post_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
